version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "master"
  ignore:
      - dependency-name: "@biomejs/biome"
      - dependency-name: "@vitest/coverage-v8"
      - dependency-name: "vitest"
